#!/usr/bin/env node

const originalEmit = process.emit;
process.emit = function (name, data, ...args) {
  if (
    name === `warning` &&
    typeof data === `object` &&
    data.name === `ExperimentalWarning` 
    && data.message.startsWith(`The Fetch API is an experimental feature.`)
  ) {
    return false;
  }
  return originalEmit.apply(process, arguments);
};

require(`${__dirname}/build/index.js`).main();