on:
  pull_request: {}
  push:
    branches: [main]

name: Build Standalone CLI

jobs:
  build_cli:
    name: Build CLI on MacOS
    runs-on: macos-latest
    env:
      APPLE_CODESIGN_CERT_ID: "F9F7EEE981D7A60F83EBEC36AD675448CA0AB41B"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ^22
          cache: yarn
          cache-dependency-path: |
            yarn.lock
      - name: Setup environment variables
        run: |
          echo "::add-mask::${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD }}"
          echo "::add-mask::${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE_BASE64 }}"

          KEYCHAIN_PASSWORD=$(openssl rand -hex 32)
          echo "::add-mask::$KEYCHAIN_PASSWORD"
          echo "KEYCHAIN_PASSWORD=$KEYCHAIN_PASSWORD" >> "$GITHUB_ENV"
      - name: Setup Keychain
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain

          echo "${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE_BASE64 }}" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          echo dir="$(yarn cache dir)" >> $GITHUB_OUTPUT
          echo version="$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-frontend-${{ steps.yarn-cache-dir-path.outputs.version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Yarn install
        run: yarn install
      - name: Build
        run: yarn build:sea

      - name: Sign build Artifact
        run: |
          codesign --timestamp --options runtime --sign "$APPLE_CODESIGN_CERT_ID" build/sea/p0
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: p0-macos
          path: build/sea/p0
