name: Semgrep CI

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: 0 1 * * *

jobs:
  semgrep:
    uses: p0-security/workflows-public/.github/workflows/semgrep-reusable.yml@main
    secrets:
      SEMGREP_RULES_APP_ID: ${{ secrets.SEMGREP_RULES_APP_ID }}
      SEMGREP_RULES_APP_PRIVATE_KEY: ${{ secrets.SEMGREP_RULES_APP_PRIVATE_KEY }}
